#!/bin/bash

# Print Dungeon Crawl Stone Soup high score list

{
    echo ' |Score|Name|Level|Type|Religion|Runes Ascended'
    for f in `ls -tr ~/.crawl/morgue/morgue-*.txt`; do
        sed -nr '
            3{
                s/([0-9]+)./\1|/
                s/ \(level ([0-9]+)/|\1/
                s/,[^,]+$//
                N
                s/\s+Began as an? /|/
                s/ on .*/|/
                N
                s/\s+Was an? (.*)\./\1/
                tg
                s/|[^|]*$//
                :g
                N
                s/\s+Escaped with the Orb//
                Th
                N
                s/\s+\.{3} and ([[:digit:]]+) runes .*/|\1/
                :h
                ti
                s/\n.*$//
                :i
                p
                q
            }
        ' <$f
    done |
    sort -nrs |
    if [[ -n $1 ]]; then
        head -n $1
    else
        cat
    fi |
    nl -s \|
} |
column -ts \| |
awk '
    NR == 1 { system("tput smso") }
    NR > 1 { sum += $2 }
    NR > 2 && NR <= 11 { system("tput setaf 250") }
    NR > 11 { system("tput setaf 240") }
    { print }
    END { print "Mean score: " (sum / (NR - 1)) }
' |
less -FXR
