#!/usr/bin/python

import re
import sys

argc = len(sys.argv)
ifd = sys.stdin if argc <= 1 else open(sys.argv[1])
ofd = sys.stdout if argc <= 2 else open(sys.argv[2], mode="w")

lnum = 10
for l in ifd:
    if not (re.match(r"('.*)?$", l) or
            re.match(r"IMMEDIATE |NEW\s*$|RUN\s*$", l, flags=re.I)):
        l = re.sub(r"\s*:'.*$", "", l)
        print(lnum, l, end="", file=ofd)
        lnum += 10

if ifd != sys.stdin:
    ifd.close()
if ofd != sys.stdout:
    ofd.close()
