#!/bin/bash

# Load LKMs needed to run a VirtualBox VM
#
# See ~/notes/vbox.txt for info on these modules as well as optional
# dependencies and maintenance info

if [[ "$UID" != "0" ]]; then
	echo 'This script must be run as root'
	exit 1
fi

modprobe vboxdrv	# Always required
modprobe vboxnetflt	# Required for host interface networking
modprobe vboxnetadp	# Required for host-only networking

echo 'Loaded:'
lsmod | grep ^vbox
