#!/bin/bash

dist_dir=~/flq/dist

usage () {
    echo "Usage: `basename $0` [WAR file (extension optional)] [dev|uat]" \
        >&2
}

if [[ $# -ne 2 ]]; then
    usage
    exit 3
fi

war_file_noext=${1%.war}
war_file=$dist_dir/$war_file_noext.war
if ! [[ -e $war_file ]]; then
    echo "File does not exist: $war_file" >&2
    exit 1
fi

shopt -s extglob
case $2 in
    dev-app|uat-app) server_log=catalina.out ;;
    *)
        usage
        exit 2
        ;;
esac
dest_host=$2
dest_dir=deploy/tmp

scp $war_file $dest_host:$dest_dir ||
    exit 4

ssh $dest_host "
    mv $dest_dir/${war_file##*/} $dest_dir/.. &&
    tail -f $server_log
"
