#!/bin/bash

case $1 in
    off) xrandr --output VGA1 --off ;;
    on) xrandr --output VGA1 --auto --right-of LVDS1 --pos 1280x0 ;;
    toggle)
        if [[ -n `
            xrandr |
            awk '
                /^VGA1/, /^DVI1/ {
                    if ($0 ~ /\*/)
                        print
                }
            '
        ` ]]; then
            $0 off
        else
            $0 on
        fi
esac
