#!/usr/bin/runhaskell

import Control.Monad

import Data.Time

import System.IO
import System.Locale
import System.Process

main = do
    putStr "Password: "
    hFlush stdout
    hSetEcho stdin False
    passwd <- getLine
    putStr "\n\n"
    hSetEcho stdin True
    forever $ do
        (Just inh, _, _, ph) <-
            createProcess $
                (shell
                    "offlineimap -o -k Repository_Remote:remotepassfile=/dev/stdin")
                    {std_in = CreatePipe}
        hPutStrLn inh passwd
        hClose inh
        waitForProcess ph
        showTime >>= putStrLn . (" *** at "++)
        getLine

showTime :: IO String
showTime = fmap (formatTime defaultTimeLocale "%H:%M:%S") getZonedTime
