#!/bin/bash

pidfile=~/tmp/olimap.pid

quit () {
    kill `<$pidfile`
    rm $pidfile
    exit
}

startmutt=false
case $1 in
    -x) quit ;;
    -m) startmutt=true ;&
    *)
        echo -n 'tmhcc account password: '
        read -s pass
        echo
        echo $pass |
        offlineimap -k Repository_Remote:remotepassfile=/dev/stdin -u quiet &
        echo $! >$pidfile
        if $startmutt; then
            mutt
            quit
        fi
        ;;
esac
