#!/bin/bash

pidfile=~/tmp/olimap.pid

quit () {
    kill $respawn_pid
    kill `<$pidfile`
    rm $pidfile
    exit
}

startmutt=false
case $1 in
    -x) quit ;;
    -m) startmutt=true ;&
    *)

        echo -n 'tmh.cc account password: '
        read -s pass
        echo

        while :; do
            echo $pass |
            offlineimap -k Repository_Remote:remotepassfile=/dev/stdin \
                -u quiet &>/dev/null &
            pid=$!
            echo $pid >$pidfile
            trap exit TERM
            wait $pid
            echo -e "\a"
        done &
        respawn_pid=$!

        if $startmutt; then
            mutt
            quit
        fi

        ;;
esac
